# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20170610_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='thana',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
