# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0007_delete_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('thana', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(choices=[(b'1', b'DHAKA'), (b'2', b'CHITTAGONG')], max_length=2)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together=set([('name', 'thana')]),
        ),
    ]
