# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20170610_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
