# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_datapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='data_category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
