# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20170616_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='DataPoint',
        ),
    ]
