# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_datapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='data_category',
            field=models.CharField(blank=True, choices=[('regular', 'REGULAR'), ('qc', 'QC')], max_length=10, null=True),
        ),
    ]
