# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 04:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20170617_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='added_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
