# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_datapoint_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
