# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0020_datapoint_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('TCHO', 'TCHO'), ('HDL-C', 'HDL-C')], max_length=50)),
                ('qc_name', models.CharField(max_length=50)),
                ('lot', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10)),
                ('value', models.IntegerField()),
                ('acceptable_range', models.CharField(max_length=100)),
                ('remarks', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Lab')),
            ],
        ),
    ]
