# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_qcdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qc',
            old_name='acceptable_from',
            new_name='lower_range',
        ),
        migrations.RenameField(
            model_name='qc',
            old_name='acceptable_to',
            new_name='upper_range',
        ),
    ]
