# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_auto_20170721_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='testparameter',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Lab'),
        ),
    ]
